name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
author: ${author}
description: ${project.description}
website: ${url}
api-version: '1.19'
load: POSTWORLD
folia-supported: true
dependencies:
  server:
    PlaceholderAPI:
      required: false
    Vault:
      required: false
    ItemEdit:
      required: false
    HeadDatabase:
      required: false
    ItemsAdder:
      required: false
    Oraxen:
      required: false
    PlayerPoints:
      required: false
    Jobs:
      required: false
    HeadDB:
      required: false
    CoinsEngine:
      required: false
    UltraEconomy:
      required: false
    TokenManager:
      required: false
    Essentials:
      required: false
    CMI:
      required: false
    Skulls:
      required: false
    MythicMobs:
      required: false
