name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${project.version}
author: ${author}
description: ${project.description}
website: ${url}
api-version: 1.13
load: POSTWORLD
softdepend:
  - PlaceholderAPI
  - Vault
  - ItemEdit
  - HeadDatabase
  - ItemsAdder
  - Oraxen
  - PlayerPoints
  - Jobs
  - HeadDB
  - CoinsEngine
  - UltraEconomy
  - TokenManager
  - Essentials
  - CMI
